version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    ports:
      - "5011:1433"
      
  sql-scriptrunner:
    image: sql-scriptrunner:latest
    build:
      context: .
      dockerfile: Sql/Sql.ScriptRunner/Dockerfile
    depends_on:
      - sqlserver
      
  redis:
    image: redis:latest
    restart: on-failure

  rabbitmq:
    image: rabbitmq:latest
    restart: on-failure
    
  ordering-api:
    image: ordering-api:latest
    build:
      context: .
      dockerfile: Ordering/Ordering.API/Dockerfile
    depends_on:
      - rabbitmq
    restart: on-failure
      
  ordering-worker:
    image: ordering-worker:latest
    build:
      context: .
      dockerfile: Ordering/Ordering.Worker/Dockerfile
    depends_on:
      - rabbitmq
    restart: on-failure
    
  catalog-api:
    image: catalog-api:latest
    build:
      context: .
      dockerfile: Catalog/Catalog.API/Dockerfile
    depends_on:
      - rabbitmq
    restart: on-failure
    
  basket-api:
    image: basket-api:latest
    build:
      context: .
      dockerfile: Basket/Basket.API/Dockerfile
    depends_on:
      - rabbitmq
      - redis
    restart: on-failure
      
  payment-api:
    image: payment-api:latest
    build:
      context: .
      dockerfile: Payment/Payment.API/Dockerfile
    depends_on:
      - rabbitmq
    restart: on-failure
  
  management-webapp:
    image: management-webapp:latest
    build:
      context: .
      dockerfile: Clients/Management.WebApp/Dockerfile
    depends_on:
      - apigateway
    restart: on-failure
    
  apigateway:
    image: apigateway:latest
    build:
      context: .
      dockerfile: Apigateways/Apigateway/Dockerfile
    depends_on:
      - catalog-api
      - basket-api
      - payment-api
    restart: on-failure