version: '3.8'

services:
  ordering-api:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://0.0.0.0:80
      ConnectionString: ${SQLCONNECTIONSTRING}   
      EventBus__SubscriptionClientName: Ordering.API
      EventBus__Connection: rabbitmq
      
  ordering-worker:
    restart: on-failure
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://0.0.0.0:80
      ConnectionString: ${SQLCONNECTIONSTRING}   
      EventBus__SubscriptionClientName: Ordering.Worker
      EventBus__Connection: rabbitmq
      CheckUpdateTimeSeconds: 10
    
  catalog-api:
    restart: on-failure
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://0.0.0.0:80
      ConnectionString: ${SQLCONNECTIONSTRING}     
      EventBus__SubscriptionClientName: Catalog.API
      EventBus__Connection: rabbitmq
      
  payment-api:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://0.0.0.0:80
      EventBus__SubscriptionClientName: Payment.API
      EventBus__Connection: rabbitmq
  
  basket-api:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://0.0.0.0:80      
      EventBus__SubscriptionClientName: Basket.API
      EventBus__Connection: rabbitmq
      RedisConnectionString: redis
    
  apigateway:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://0.0.0.0:80
    ports:
      - "5010:80"