version: '3.8'

services:
  sqlserver:
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: Asdf1234!

  sql-scriptrunner:
    environment:
      ConnectionString: "server=sqlserver;database=master;user=sa;password=Asdf1234!"

  ordering-api:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://0.0.0.0:80
      ConnectionString: ${SQLCONNECTIONSTRING}   
      EventBus__SubscriptionClientName: Ordering.API
      EventBus__Connection: rabbitmq
      
  ordering-worker:
    environment:
      ASPNETCORE_ENVIRONMENT: Relase
      ASPNETCORE_URLS: http://0.0.0.0:80
      ConnectionString: ${SQLCONNECTIONSTRING}   
      EventBus__SubscriptionClientName: Ordering.Worker
      EventBus__Connection: rabbitmq
      CheckUpdateTimeSeconds: 10
    
  catalog-api:
    environment:
      ASPNETCORE_ENVIRONMENT: Relase
      ASPNETCORE_URLS: http://0.0.0.0:80
      ConnectionString: ${SQLCONNECTIONSTRING}     
      EventBus__SubscriptionClientName: Catalog.API
      EventBus__Connection: rabbitmq
      
  payment-api:
    environment:
      ASPNETCORE_ENVIRONMENT: Relase
      ASPNETCORE_URLS: http://0.0.0.0:80
      EventBus__SubscriptionClientName: Payment.API
      EventBus__Connection: rabbitmq
  
  basket-api:
    environment:
      ASPNETCORE_ENVIRONMENT: Relase
      ASPNETCORE_URLS: http://0.0.0.0:80      
      EventBus__SubscriptionClientName: Basket.API
      EventBus__Connection: rabbitmq
      RedisConnectionString: redis
    
  management-webapp:
    environment:
      ASPNETCORE_ENVIRONMENT: Relase
      ASPNETCORE_URLS: http://0.0.0.0:80
      ApiOptions__BaseAddress: "http://apigateway"
      ApiOptions__BrandAddress: "/c/brand"
      ApiOptions__TypeAddress: "/c/type"
      ApiOptions__CatalogAddress: "/c/catalog"
    ports:
      - "5012:80"

  apigateway:
    environment:
      ASPNETCORE_ENVIRONMENT: Relase
      ASPNETCORE_URLS: http://0.0.0.0:80
    ports:
      - "5010:80"